---
train:

    params:
        batch_size: 512
        epoch: 10
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "checkpoints/"
        folder: mpii
        model_name: trans6
        step: 10

    data:
        image: "../../datasets/processed/MPII_2d/Image"
        label: "../../datasets/processed/MPII_2d/Label"
        header: True
        name: mpii
        isFolder: True
        
    pretrain:
        enable: False
        path: "xx/xx.pt"
        device: 0

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
