---
demo:

    load:
        path: "checkpoints/mpii/checkpoint/Iter_80_trans6.pt"
        device: 0

    data: 
        image: "../../datasets/processed/MPII_2d/Image/p00/face/1.jpg"
        label: "../../datasets/processed/MPII_2d/Label"
        name: mpii
        header: True
        isFolder: False

    savename: "demo"

    logname: "0612.log"

    device:
        usegpu: False
        device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
